version: "2"
services:
  app:
    build: .
    container_name: "vuttr-node-js"
    command: sh -c "npm run sequelize db:migrate && npm run start"
    volumes:
      - ./:/app
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_USER}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml