version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
     - app-connect
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml
    networks:
     - app-connect
  app:
    env_file: 
     - .env
    build: .
    depends_on:
      - db
    container_name: "vuttr-node-js"  
    command: npm run-script dev
    ports:
      - 3000:3000
    volumes:
     - .:/src/app
    environment:
      DB_HOST: db
    networks:
     - app-connect
networks:
    app-connect:
        driver: bridge
volumes:
    data: