swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger Vuttr"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/"
tags:
- name: "users"
  description: "Operations about user"
- name: "tools"
  description: "Access to tools"
  externalDocs:
    description: ""
    url: "http://swagger.io"
schemes:
- "http"
securityDefinitions:  
   Bearer:    
     type: apiKey    
     name: Authorization    
     in: header
paths:
  /users:
    post:
      tags:
      - "users"
      summary: "Create user"
      description: "Create user."
      operationId: "createUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/schemas/CreateUser"
      responses:
        201:
          description: "successful operation" 
  /sessions:
     post:
      description: 'Returns token for authorized User'
      tags: [users]
      operationId: Login
      consumes:
        - "application/json"
      parameters:
        - name: 'login'
          in: 'body'
          required: true
          description: 'Login Payload'
          schema:
            $ref: '#/schemas/Login'
      responses:
        200:
          schema:
            $ref: '#/schemas/SuccessLogin'
          description: Token
  /tools:
    get:
      tags:
      - "tools"
      summary: "Returns all tools saves"
      description: "Returns all tools saves"
      operationId: "getTools"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
  /tools/{tag}:
   get:
    tags:
    - "tools"
    summary: "Find purchase tool by tag"
    description: ""
    operationId: ""
    produces:
    - "application/xml"
    - "application/json"
    parameters:
    - name: "tag"
      in: "path"
      description: "Tag of tools that needs to be fetched"
      required: true
      type: "integer"
      maximum: 10.0
      minimum: 1.0
      format: "int64"
    responses:
      "200":
        description: "successful operation"
        schema:
          $ref: "#/definitions/Tools"
      "400":
        description: "Invalid ID supplied"
      "404":
        description: "Tools not found"
  /tools/:
    post:
      tags:
      - "tools"
      summary: "Place an new tool"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Create tool"
        required: true
        schema:
          $ref: "#/definitions/Tools"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Tools"
        "400":
          description: "Invalid Tools"
  /tools/{id}/:
    delete:
      tags:
      - "tools"
      summary: "Delete purchase tool by ID"
      description: "For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors"
      operationId: "delete"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the tool that needs to be deleted"
        required: true
        type: "integer"
        minimum: 1.0
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "tool not found"
definitions:
  Users:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
  Tools:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      link:
        type: "string"
      title:
        type: "string"
      description:
        type: "string"
      tags:
        type: "array"
        items: {}
    xml:
      name: "Tools"
schemas:
    SuccessLogin:
      type: object
      properties:
        User:
           type: "array"
           items:
            oneOf:
            - type: integer
            - type: string
            - type: string
        Token:
          type: string
      required:
        - code
        - message
    Login:
      type: object
      properties:
        email:
           type: "string"
        password:
          type: "string"
      required:
        - code
        - message
    CreateUser:
      type: object
      properties:
        name:
          type: "string"
        email:
           type: "string"
        password:
          type: "string"
      required:
        - code
        - message
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"