name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
       yarn
       yarn test
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USERNAME }}
       key: ${{ secrets.KEY }}
       port: ${{ secrets.PORT }}
       script: |
          git stash save 'Config production'
          git pull 
          sudo docker stop $(docker ps -a -q)
          git stash pop stash@{0}
          npm run-script build  
          sudo docker-compose build
          sudo docker-compose up -d